In [4]:
import pandas as pd 

airports = pd.read_csv('airportCodesTypeFiltered.csv')

airports.tail(30)

#values_to_drop = ['NaN']
#df_filtered = airports[~airports['iata_code'].isin(values_to_drop)]

#df_filtered.head()

airports.dropna(subset=['iata_code'], inplace=True)

airports.head()

#check to see if filtering the types removes the duplicate iata codes
#need to remove NaN
#make a list of all the vlaues in iata_codes, before adding check if already there. if already that code is already
#there then break from loop and print "Dupes exist" whil printing the dupes

,Unnamed: 0,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
121,222,03N,small_airport,Utirik Airport,4.0,OC,MH,MH-UTI,Utirik Island,K03N,UTK,03N,"169.852005, 11.222"
249,440,07FA,small_airport,Ocean Reef Club Airport,8.0,NaN,US,US-FL,Key Largo,07FA,OCA,07FA,"-80.274803161621, 25.325399398804"
345,597,0AK,small_airport,Pilot Station Airport,305.0,NaN,US,US-AK,Pilot Station,NaN,PQS,0AK,"-162.899994, 61.934601"
385,676,0CO2,small_airport,Crested Butte Airpark,8980.0,NaN,US,US-CO,Crested Butte,0CO2,CSE,0CO2,"-106.928341, 38.851918"
623,1093,0TE7,small_airport,LBJ Ranch Airport,1515.0,NaN,US,US-TX,Johnson City,0TE7,JCY,0TE7,"-98.62249755859999, 30.251800537100003"

In [5]:
# Check for duplicate entries in the 'Iata_codes' column
duplicates = airports['iata_code'].duplicated()

# The 'duplicated' method returns a boolean Series where True indicates a duplicate entry

# If you want to see the rows with duplicate entries, you can use boolean indexing
duplicate_rows = airports[duplicates]

# If you just want to count the number of duplicates, you can use the sum() method
num_duplicates = duplicates.sum()

# Print or use the results as needed
print("Number of duplicate entries:", num_duplicates)
print("Rows with duplicate entries:")
print(duplicate_rows)

Number of duplicate entries: 96
Rows with duplicate entries:
       Unnamed: 0   ident            type  \
13322       21533    FNBL   small_airport
18701       28343  KE-MRE   small_airport
19767       29469     KMM   small_airport
26543       39494    OPDD   small_airport
27027       40091     PCO   small_airport
...           ...     ...             ...
37346       54337    WILP   small_airport
37498       54533    WPMN   small_airport
37508       54543    WRKR   small_airport
38922       56212     YNT   large_airport
39830       57285    ZSYA  medium_airport

                                       name  elevation_ft continent  \
13322                       Lumbala Airport        3700.0        AF
18701                   Mara Lodges Airport        5706.0        AF
19767                        Kimaam Airport          26.0        AS
26543                          Dadu Airport         121.0        AS
27027                Punta Colorada Airport          55.0       NaN
...                                     ...           ...       ...
37346        Muhammad Taufiq Kiemas Airport         118.0        AS
37498                       Maliana Airport           NaN        AS
37508     David Constantijn Saudale Airport         470.0        AS
38922  Yantai Penglai International Airport         154.0        AS
39830              Yangzhou Taizhou Airport           7.0        AS

      iso_country iso_region          municipality gps_code iata_code  \
13322          AO     AO-MOX      Lumbala N'guimbo     FNBL       GGC
18701          KE     KE-700           Mara Lodges      NaN       MRE
19767          ID      ID-PA                Kimaam      NaN       KMM
26543          PK      PK-SD                  Dadu     OPDD       DDU
27027          MX     MX-BCS             La Ribera     MMPL       PCO
...           ...        ...                   ...      ...       ...
37346          ID      ID-LA                  Krui     WILP       TFY
37498          TL      TL-BO               Maliana     WPMN       MPT
37508          ID      ID-NT    Ba'a - Rote Island     WATR       RTI
38922          CN      CN-37                Yantai     ZSYT       YNT
39830          CN      CN-32  Yangzhou and Taizhou     ZSYA       YTY

      local_code                             coordinates
13322        NaN                    21.45083, -14.105106
18701        NaN  35.11130905151367, -1.1782759428024292
19767        NaN            138.852005005, -7.9781999588
26543        NaN        67.67459869380001, 26.5545005798
27027        PCL                  -109.535826, 23.575011
...          ...                                     ...
37346        NaN                   103.936501, -5.211562
37498        NaN                    125.214996, -8.97224
37508        NaN                      123.0747, -10.7673
38922        NaN                   120.987222, 37.657222
39830        NaN                       119.7198, 32.5634

[96 rows x 13 columns]